# Generated by Django 3.0.4 on 2020-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'unique_together': {('name', 'number')},
            },
        ),
    ]
